name: portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0-278.2.beta

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  riverpod_annotation:  ^2.1.0
  flutter_svg: ^2.2.0
  gap: ^3.0.1
  intl: any
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  riverpod_generator: ^2.2.0
  build_runner: ^2.4.0

flutter:
  generate: true
  uses-material-design: true

  assets:
  - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins.regular.ttf
        - asset: assets/fonts/poppins.medium.ttf
        - asset: assets/fonts/poppins.bold.ttf
    - family: YongYeang
      fonts:
        - asset: assets/fonts/Angkor-Regular.ttf
        # - asset: assets/fonts/Kh Ang PhkayProek.ttf
        # - asset: assets/fonts/Kh Ang NiTean.ttf

